### ISSUE TITLE
Issue parsing ampersands in strings

### ISSUE THREAD

**Issue by nathany** [ciaran/plist#4] opened 2016-03-18 23:28 UTC
An XML plist file containing:

```
<string>foo &amp; bar</string>`
```

Produces an error as follows:

```
     ** (FunctionClauseError) no function clause matching in Plist.XML.parse_value/2
     stacktrace:
       (plist) lib/xml.ex:28: Plist.XML.parse_value(:string, [{:xmlText, [string: 20, dict: 2, plist: 1], 1, [], 'foo ', :text}, {:xmlText, [string: 20, dict: 2, plist: 1], 2, [], '& bar', :text}])
       (plist) lib/xml.ex:77: anonymous fn/1 in Plist.XML.parse_value/2
```

**Comment by idyll** [comment] 2016-03-19 04:26
The issue is xml.ex 28-30

```
  defp parse_value(:string, [text]) do
    text |> xmlText(:value) |> :binary.list_to_bin
  end
```

`[text]` isn't always an array with a single element.
In this case there are two elements caused by merl converting `&amp;`.

**Comment by idyll** [comment] 2016-03-19 04:39
I think you can fix this by adding another function:

```
  defp parse_value(:string, [text | list]) do
    parse_value(:string, [text]) <> parse_value(:string, list)
  end
```

**Comment by ciaran** [comment] 2016-03-19 19:23
Fixed in latest version.

(Note that the above code would not be tail-optimised due to the concatenate, so it would add to the stack each time a new node is processed)

**Closed as completed by ciaran** 2016-03-19 19:23 UTC
